name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - name: "Build with Gradle"
            command: "build -x lint -x test"
          - name: "Check lint"
            command: "lint"
          - name: "Run local tests"
            command: "test"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Java and Gradle Cache
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run - ${{ matrix.task.name }}
        run: ./gradlew ${{ matrix.task.command }}
